name: Frontend - CI/CD

on:
  push:
    path:
      - 'frontend/**'
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm install

      - name: Rodar testes
        run: npm run test

      - name: Deploy na Vercel
        run: npx vercel --prod --token={{ secrets.VERCEL_TOKEN }}  