name: Frontend - CI/CD

on:
  push:
    path:
      - 'frontend/**'
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm install

      - name: Rodar testes
        run: npm run test

      - name: Building
        run: npm run build

      - name: Push no repositório
        run: git push origin main